// <auto-generated />
using System;
using HotelBookingSystem.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HotelBookingSystem.Migrations
{
    [DbContext(typeof(HotelDbContext))]
    [Migration("20260417171423_AddIsActiveToEmployee")]
    partial class AddIsActiveToEmployee
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HotelBookingSystem.Models.Booking", b =>
                {
                    b.Property<int>("Bookingid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("bookingid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Bookingid"));

                    b.Property<DateTime?>("Checkindate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("checkindate");

                    b.Property<DateTime?>("Checkoutdate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("checkoutdate");

                    b.Property<int?>("Clientid")
                        .HasColumnType("integer")
                        .HasColumnName("clientid");

                    b.Property<DateTime?>("Createdat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("createdat")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int?>("Employeeid")
                        .HasColumnType("integer")
                        .HasColumnName("employeeid");

                    b.Property<int?>("Roomid")
                        .HasColumnType("integer")
                        .HasColumnName("roomid");

                    b.Property<decimal?>("Roompriceatbooking")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("roompriceatbooking");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<decimal?>("Totalprice")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("totalprice");

                    b.Property<DateTime?>("Updatedat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updatedat")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Bookingid")
                        .HasName("bookings_pkey");

                    b.HasIndex("Clientid");

                    b.HasIndex("Employeeid");

                    b.HasIndex("Roomid");

                    b.ToTable("bookings", (string)null);
                });

            modelBuilder.Entity("HotelBookingSystem.Models.BookingHistory", b =>
                {
                    b.Property<int>("Historyid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("historyid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Historyid"));

                    b.Property<int?>("Bookingid")
                        .HasColumnType("integer")
                        .HasColumnName("bookingid");

                    b.Property<DateTime?>("Changeddate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("changeddate")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Newstatus")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("newstatus");

                    b.Property<string>("Oldstatus")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("oldstatus");

                    b.HasKey("Historyid")
                        .HasName("booking_history_pkey");

                    b.HasIndex("Bookingid");

                    b.ToTable("booking_history", (string)null);
                });

            modelBuilder.Entity("HotelBookingSystem.Models.BookingService", b =>
                {
                    b.Property<int>("Bookingid")
                        .HasColumnType("integer")
                        .HasColumnName("bookingid");

                    b.Property<int>("Serviceid")
                        .HasColumnType("integer")
                        .HasColumnName("serviceid");

                    b.Property<decimal?>("Priceatbooking")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("priceatbooking");

                    b.Property<int?>("Quantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("quantity");

                    b.HasKey("Bookingid", "Serviceid")
                        .HasName("booking_services_pkey");

                    b.HasIndex("Serviceid");

                    b.ToTable("booking_services", (string)null);
                });

            modelBuilder.Entity("HotelBookingSystem.Models.Client", b =>
                {
                    b.Property<int>("Clientid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("clientid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Clientid"));

                    b.Property<DateTime?>("Createdat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("createdat")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("email");

                    b.Property<string>("Fullname")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("fullname");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Phonenumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phonenumber");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<DateTime?>("Updatedat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updatedat")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.HasKey("Clientid")
                        .HasName("clients_pkey");

                    b.HasIndex(new[] { "Email" }, "clients_email_key")
                        .IsUnique();

                    b.ToTable("clients", (string)null);
                });

            modelBuilder.Entity("HotelBookingSystem.Models.Employee", b =>
                {
                    b.Property<int>("Employeeid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("employeeid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Employeeid"));

                    b.Property<DateTime?>("Createdat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("createdat")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("email");

                    b.Property<string>("Fullname")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("fullname");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Phonenumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phonenumber");

                    b.Property<string>("Position")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("position");

                    b.Property<decimal?>("Salary")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("salary");

                    b.Property<DateTime?>("Updatedat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updatedat")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.HasKey("Employeeid")
                        .HasName("employees_pkey");

                    b.HasIndex(new[] { "Email" }, "employees_email_key")
                        .IsUnique();

                    b.ToTable("employees", (string)null);
                });

            modelBuilder.Entity("HotelBookingSystem.Models.Medium", b =>
                {
                    b.Property<int>("Mediaid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("mediaid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Mediaid"));

                    b.Property<DateTime?>("Createdat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("createdat")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int?>("Entityid")
                        .HasColumnType("integer")
                        .HasColumnName("entityid");

                    b.Property<string>("Entitytype")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("entitytype");

                    b.Property<string>("Filetype")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("filetype");

                    b.Property<bool?>("Isprimary")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("isprimary");

                    b.Property<DateTime?>("Updatedat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updatedat")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Url")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("url");

                    b.HasKey("Mediaid")
                        .HasName("media_pkey");

                    b.ToTable("media", (string)null);
                });

            modelBuilder.Entity("HotelBookingSystem.Models.Room", b =>
                {
                    b.Property<int>("Roomid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("roomid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Roomid"));

                    b.Property<int?>("Capacity")
                        .HasColumnType("integer")
                        .HasColumnName("capacity");

                    b.Property<DateTime?>("Createdat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("createdat")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<decimal?>("Pricepernight")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("pricepernight");

                    b.Property<string>("Roomnumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("roomnumber");

                    b.Property<string>("Roomtype")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("roomtype");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<DateTime?>("Updatedat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updatedat")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Roomid")
                        .HasName("rooms_pkey");

                    b.HasIndex(new[] { "Roomnumber" }, "rooms_roomnumber_key")
                        .IsUnique();

                    b.ToTable("rooms", (string)null);
                });

            modelBuilder.Entity("HotelBookingSystem.Models.Service", b =>
                {
                    b.Property<int>("Serviceid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("serviceid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Serviceid"));

                    b.Property<DateTime?>("Createdat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("createdat")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsAvailable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_available");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<decimal?>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("price");

                    b.Property<DateTime?>("Updatedat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updatedat")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Serviceid")
                        .HasName("services_pkey");

                    b.ToTable("services", (string)null);
                });

            modelBuilder.Entity("HotelBookingSystem.Models.Booking", b =>
                {
                    b.HasOne("HotelBookingSystem.Models.Client", "Client")
                        .WithMany("Bookings")
                        .HasForeignKey("Clientid")
                        .HasConstraintName("bookings_clientid_fkey");

                    b.HasOne("HotelBookingSystem.Models.Employee", "Employee")
                        .WithMany("Bookings")
                        .HasForeignKey("Employeeid")
                        .HasConstraintName("bookings_employeeid_fkey");

                    b.HasOne("HotelBookingSystem.Models.Room", "Room")
                        .WithMany("Bookings")
                        .HasForeignKey("Roomid")
                        .HasConstraintName("bookings_roomid_fkey");

                    b.Navigation("Client");

                    b.Navigation("Employee");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("HotelBookingSystem.Models.BookingHistory", b =>
                {
                    b.HasOne("HotelBookingSystem.Models.Booking", "Booking")
                        .WithMany("BookingHistories")
                        .HasForeignKey("Bookingid")
                        .HasConstraintName("booking_history_bookingid_fkey");

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("HotelBookingSystem.Models.BookingService", b =>
                {
                    b.HasOne("HotelBookingSystem.Models.Booking", "Booking")
                        .WithMany("BookingServices")
                        .HasForeignKey("Bookingid")
                        .IsRequired()
                        .HasConstraintName("booking_services_bookingid_fkey");

                    b.HasOne("HotelBookingSystem.Models.Service", "Service")
                        .WithMany("BookingServices")
                        .HasForeignKey("Serviceid")
                        .IsRequired()
                        .HasConstraintName("booking_services_serviceid_fkey");

                    b.Navigation("Booking");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("HotelBookingSystem.Models.Booking", b =>
                {
                    b.Navigation("BookingHistories");

                    b.Navigation("BookingServices");
                });

            modelBuilder.Entity("HotelBookingSystem.Models.Client", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("HotelBookingSystem.Models.Employee", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("HotelBookingSystem.Models.Room", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("HotelBookingSystem.Models.Service", b =>
                {
                    b.Navigation("BookingServices");
                });
#pragma warning restore 612, 618
        }
    }
}
